//! Protobuf definitions and generated code for Raft communication.
//!
//! This module contains the generated Rust code from `proto/raft.proto`.
//! The code is generated by `tonic-build` during the build process and
//! included here via the `include!` macro.
//!
//! The generated code includes:
//! - Request and response message types (e.g., `VoteRequest`, `AppendEntriesResponse`).
//! - gRPC service definitions (`RaftService`).
//! - Client and server implementations.
//!
//! Note: The actual generated file is located in the `OUT_DIR` directory
//! (e.g., `target/debug/build/openraft-surrealkv-<hash>/out/raft.rs`).

pub mod raft {
    // Include the generated code from OUT_DIR.
    // This avoids modifying the source tree during build, which fixes
    // "Source directory was modified by build.rs during cargo publish" errors.
    include!(concat!(env!("OUT_DIR"), "/raft.rs"));
}

pub use raft::*;
