on:
  push:
    branches:
      - main

name: Docs

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: 'recursive'
          
      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "33.1"
          repo-token: ${{ inputs.github-token }}

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake libclang-dev

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo doc
        run: cargo doc --no-deps --all-features